/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import AccesoADatos.AlumnoData;
import Entidades.Alumno;

/**
 *
 * @author agust
 */
public class FormularioDeInscripcion extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioDeInscripcion
     */
    public FormularioDeInscripcion() {
        initComponents();
        CargarComboBox ();
        ArmarCabecera();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFormularioDeInscripcion = new javax.swing.JLabel();
        jLSeleccionAlumno = new javax.swing.JLabel();
        jListadoDeMaterias = new javax.swing.JLabel();
        jRMateriasInscriptas = new javax.swing.JRadioButton();
        jRmateriasNoInscriptas = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaAlumnos = new javax.swing.JTable();
        jBinscribir = new javax.swing.JButton();
        jBanularInscripcion = new javax.swing.JButton();
        JBsalir = new javax.swing.JButton();
        jcbSeleccionA = new javax.swing.JComboBox<>();

        JFormularioDeInscripcion.setText("                             Formulario De Inscripcion");

        jLSeleccionAlumno.setText("Seleccione un Alumno");

        jListadoDeMaterias.setText("Listado de Materias");

        jRMateriasInscriptas.setText("Materias Inscriptas");

        jRmateriasNoInscriptas.setText("Materias No Inscriptas");

        jTablaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablaAlumnos);

        jBinscribir.setText("Inscribir");

        jBanularInscripcion.setText("Anular Inscripcion");

        JBsalir.setText("Salir");

        jcbSeleccionA.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbSeleccionAItemStateChanged(evt);
            }
        });
        jcbSeleccionA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSeleccionAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jListadoDeMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbSeleccionA, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBsalir, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLSeleccionAlumno)
                            .addComponent(jRMateriasInscriptas)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBinscribir)
                                .addGap(95, 95, 95)
                                .addComponent(jBanularInscripcion))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(269, 269, 269)
                                .addComponent(jRmateriasNoInscriptas))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JFormularioDeInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JFormularioDeInscripcion)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSeleccionAlumno)
                    .addComponent(jcbSeleccionA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jListadoDeMaterias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRMateriasInscriptas)
                    .addComponent(jRmateriasNoInscriptas))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBinscribir)
                    .addComponent(jBanularInscripcion)
                    .addComponent(JBsalir))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbSeleccionAItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbSeleccionAItemStateChanged
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jcbSeleccionAItemStateChanged

    private void jcbSeleccionAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSeleccionAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSeleccionAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBsalir;
    private javax.swing.JLabel JFormularioDeInscripcion;
    private javax.swing.JButton jBanularInscripcion;
    private javax.swing.JButton jBinscribir;
    private javax.swing.JLabel jLSeleccionAlumno;
    private javax.swing.JLabel jListadoDeMaterias;
    private javax.swing.JRadioButton jRMateriasInscriptas;
    private javax.swing.JRadioButton jRmateriasNoInscriptas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaAlumnos;
    private javax.swing.JComboBox<Alumno> jcbSeleccionA;
    // End of variables declaration//GEN-END:variables

    private void ArmarCabecera(){
        
//        modelo.addColumn("ID");
//        modelo.addColumn("-NOMBRE");
//        modelo.addColumn("AÑO");
//    
    }

   private void CargarComboBox (){
    
       AlumnoData lista= new AlumnoData () ;
       
       jcbSeleccionA.addItem((Alumno) lista.listarAlumnos()) ;
       JFormularioDeInscripcion.setVisible(true);
   }
   

}

